"""Writes scripts/icons-data.mjs: the site's icons as SVG paths (round 5).

Local-only helper (Python + fontTools), kept for the record of where the paths
came from. It read the icon names and code points from the Font Awesome Free
6.0.0 subset CSS and the glyph outlines from the two subset fonts the site used
until round 5, and converted each glyph to a compact relative SVG path (y
flipped, baseline at 448 of a 512 em, as in Font Awesome's own SVGs).
To add an icon now, take its path from Font Awesome Free 6 (viewBox 0 0 W 512)
and add it to scripts/icons-data.mjs by hand.

Font Awesome Free icons: CC BY 4.0, https://fontawesome.com/license/free

usage: python scripts/extract_icons.py <icons.css> <fa-solid.woff2> <fa-brands.woff2>
"""
import json
import re
import sys
from pathlib import Path

from fontTools.pens.basePen import BasePen
from fontTools.ttLib import TTFont


def num(v):
    v = round(v, 2)
    s = ("%d" % v) if v == int(v) else ("%.2f" % v).rstrip("0")
    return s.replace("0.", ".", 1) if s.startswith("0.") else s.replace("-0.", "-.", 1)


def join(values):
    out = ""
    for v in values:
        s = num(v)
        out += s if (not out or s.startswith("-") or (s.startswith(".") and "." in out.split(" ")[-1] and not out[-1].isalpha())) else " " + s
    return out


class RelPathPen(BasePen):
    """Relative, minimal SVG path commands (y flipped around 448)."""

    def __init__(self, glyphset):
        super().__init__(glyphset)
        self.d = []
        self.cx = self.cy = 0.0
        self.sx = self.sy = 0.0

    def _p(self, pt):
        return pt[0], 448 - pt[1]

    def _moveTo(self, pt):
        x, y = self._p(pt)
        self.d.append("m" + join([x - self.cx, y - self.cy]) if self.d else "M" + join([x, y]))
        self.cx, self.cy = self.sx, self.sy = x, y

    def _lineTo(self, pt):
        x, y = self._p(pt)
        dx, dy = x - self.cx, y - self.cy
        if dy == 0:
            self.d.append("h" + join([dx]))
        elif dx == 0:
            self.d.append("v" + join([dy]))
        else:
            self.d.append("l" + join([dx, dy]))
        self.cx, self.cy = x, y

    def _qCurveToOne(self, p1, p2):
        (x1, y1), (x, y) = self._p(p1), self._p(p2)
        self.d.append("q" + join([x1 - self.cx, y1 - self.cy, x - self.cx, y - self.cy]))
        self.cx, self.cy = x, y

    def _curveToOne(self, p1, p2, p3):
        (x1, y1), (x2, y2), (x, y) = self._p(p1), self._p(p2), self._p(p3)
        self.d.append("c" + join([x1 - self.cx, y1 - self.cy, x2 - self.cx, y2 - self.cy, x - self.cx, y - self.cy]))
        self.cx, self.cy = x, y

    def _closePath(self):
        self.d.append("z")
        self.cx, self.cy = self.sx, self.sy


css_path, solid_path, brands_path = sys.argv[1:4]
css = Path(css_path).read_text(encoding="utf8")
BRANDS = {"facebook", "facebook-f", "google"}
fonts = {"solid": TTFont(solid_path), "brands": TTFont(brands_path)}
icons = {}
for name, code in re.findall(r"\.fa-([a-z0-9-]+)::before\s*\{\s*content:\s*\"\\([0-9a-f]+)\"", css):
    font = fonts["brands" if name in BRANDS else "solid"]
    if font["head"].unitsPerEm != 512:
        raise SystemExit("unexpected unitsPerEm")
    glyph_name = font.getBestCmap().get(int(code, 16))
    if glyph_name is None:
        raise SystemExit(f"{name}: U+{code} not in the subset font")
    gs = font.getGlyphSet()
    pen = RelPathPen(gs)
    gs[glyph_name].draw(pen)
    # repeated commands may drop their letter (SVG implicit repetition)
    d, prev = "", ""
    for cmd in pen.d:
        letter, args = cmd[0], cmd[1:]
        if letter == prev and letter in "lqch" + "v" and args:
            d += args if args.startswith("-") else " " + args
        else:
            d += cmd
        prev = letter
    icons[name] = {"w": font["hmtx"][glyph_name][0], "d": d}

out = Path(__file__).with_name("icons-data.mjs")
body = ",\n".join(f"  {json.dumps(k)}: {json.dumps(v, separators=(',', ':'))}" for k, v in sorted(icons.items()))
out.write_text(
    "// Generated by scripts/extract_icons.py from the Font Awesome Free 6.0.0 subset\n"
    "// (icons: CC BY 4.0, https://fontawesome.com/license/free).\n"
    f"export const ICONS = {{\n{body},\n}};\n",
    encoding="utf8",
)
print(f"{len(icons)} icons -> {out} ({out.stat().st_size} bytes)")
