#!/usr/bin/env node
/**
 * generate_local_pages.js — bilingual local service-area pages for
 * hernandezlandscapeservices.com (Sycamore, Cortland, Malta).
 *
 * Usage: node scripts/generate_local_pages.js          (write pages + sitemap)
 *        node scripts/generate_local_pages.js --check  (exit 1 on drift, CI-safe)
 *
 * What it owns (regenerated between explicit markers / full files):
 *   - service-areas/malta-il/index.html                (EN, full file, @generated)
 *   - es/service-areas/<city>-il/index.html            (ES, full files, @generated)
 *   - the HREFLANG:GENERATED block inside the existing hand-written EN pages
 *     for Sycamore and Cortland (three <link rel="alternate"> tags after the
 *     canonical — nothing else in those files is touched)
 *   - the LOCAL-PAGES:GENERATED block in sitemap.xml (one <url> entry per
 *     generator-owned page)
 *
 * The Spanish copy is hand-written per city in CITY_PAGES below — it is not a
 * machine translation of the English page, and each city keeps its own local
 * angle so no two pages read alike. Every page carries a full head (canonical,
 * og/twitter incl. og:image:alt, robots) plus JSON-LD, so it passes
 * scripts/check-seo.mjs. hreflang mapping: en <-> es, x-default -> en.
 *
 * Idempotent: running twice produces zero diff (lastmod is a fixed constant).
 * Requires Node 18+; no dependencies.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://hernandezlandscapeservices.com';
const CHECK = process.argv.includes('--check');
// Fixed so --check stays drift-free between runs; bump when copy changes.
const LASTMOD = '2026-07-06';

const BANNER =
  '<!-- @generated by scripts/generate_local_pages.js — do not hand-edit.\n' +
  '     Update the copy in that script, then re-run: node scripts/generate_local_pages.js -->';

const HREFLANG_START = '<!-- HREFLANG:GENERATED:START -->';
const HREFLANG_END = '<!-- HREFLANG:GENERATED:END -->';
const SITEMAP_START = '<!-- LOCAL-PAGES:GENERATED:START -->';
const SITEMAP_END = '<!-- LOCAL-PAGES:GENERATED:END -->';

/* ------------------------------------------------------------------------ */
/* Per-city page copy. EN blocks exist only for cities whose English page is  */
/* generator-owned (Malta); Sycamore and Cortland EN pages stay hand-written. */
/* ------------------------------------------------------------------------ */

const CITY_PAGES = [
  {
    slug: 'sycamore-il',
    ownsEn: false,
    image: '/hernandez_images/google-profile-2026-tree-climber-canopy.jpg',
    es: {
      title: 'Jardinería y servicio de árboles en Sycamore, IL | Hernandez Landscape',
      description:
        'Hernandez Landscape & Tree Service LLC atiende Sycamore, IL con corte de pasto, jardinería, poda y retiro de árboles, limpieza y servicio de nieve. Llame al (815) 501-1478.',
      ogDescription:
        'Corte de pasto, jardinería, servicio de árboles y limpieza en Sycamore — empresa familiar local, se habla español.',
      imageAlt: 'Trabajador del equipo de árboles en la copa de un árbol cerca de casas en Sycamore',
      kicker: 'Sycamore, Illinois',
      h1: 'Jardinería, corte de pasto y servicio de árboles en Sycamore',
      intro:
        'Para las casas de Sycamore, Hernandez Landscape & Tree Service LLC ofrece corte de pasto regular, limpieza de jardines, mantillo y plantas, poda y retiro de árboles, y limpieza después de tormentas según disponibilidad. Empresa familiar local — lo atendemos en español.',
      ctaText: 'Pida su presupuesto en Sycamore',
      ctaHref: '/?service=tree-service#quote',
      cardsTitle: 'Trabajo de patio para propiedades de Sycamore',
      cards: [
        { href: '/lawn-care/', h3: 'Mantenimiento de pasto', p: 'Corte, orillado y mantenimiento regular del pasto para patios residenciales de Sycamore.' },
        { href: '/tree-removal/', h3: 'Poda y retiro de árboles', p: 'Cortes cuidadosos, acarreo y limpieza cuando los árboles estorban casas, cercas o entradas.' },
        { href: '/#services', h3: 'Limpieza de jardín', p: 'Mantillo, camas de plantas, limpieza de temporada, hojas y mejoras para la fachada de su casa.' }
      ],
      nearH2: 'Un equipo local muy cerca de Sycamore',
      nearP:
        'La base del negocio está en DeKalb, así que Sycamore queda a unos minutos para presupuestos, mantenimiento regular y trabajos programados.',
      faqTitle: 'Preguntas frecuentes en Sycamore',
      faq: [
        { q: '¿Dan presupuestos en Sycamore?', a: 'Sí. Hay presupuestos disponibles en Sycamore para pasto, árboles, jardinería, limpieza y nieve según disponibilidad.' },
        { q: '¿Limpian después de retirar un árbol?', a: 'Sí. La limpieza y el acarreo se incluyen en el presupuesto del servicio de árboles cuando se solicitan.' },
        { q: '¿Atienden en español?', a: 'Sí. Puede llamar al (815) 501-1478 y explicar su proyecto en español con confianza.' }
      ],
      breadcrumbCity: 'Sycamore, IL',
      sitemapImageTitle: 'Servicio de árboles en Sycamore IL',
      sitemapImageCaption: 'Trabajo del equipo de árboles de Hernandez Landscape & Tree Service LLC cerca del área de Sycamore.'
    }
  },
  {
    slug: 'cortland-il',
    ownsEn: false,
    image: '/hernandez_images/facebook-2026-side-yard-lawn-finish.jpg',
    es: {
      title: 'Corte de pasto y jardinería en Cortland, IL | Hernandez Landscape',
      description:
        'Corte de pasto, limpieza de jardines, mantillo y servicio de árboles para casas de Cortland, IL. Hernandez Landscape & Tree Service LLC — llame al (815) 501-1478.',
      ogDescription:
        'Corte de pasto, renovación de jardines, limpieza y servicio de árboles para propiedades de Cortland.',
      imageAlt: 'Pasto verde recién terminado en un patio lateral cerca de Cortland, Illinois',
      kicker: 'Cortland, Illinois',
      h1: 'Corte de pasto, jardinería y limpieza en Cortland',
      intro:
        'Hernandez Landscape & Tree Service LLC ayuda a los dueños de casa en Cortland con corte de pasto, limpiezas, renovación de jardines, servicio de árboles y apoyo con nieve en invierno según disponibilidad. Lo atendemos en español.',
      ctaText: 'Pida su presupuesto en Cortland',
      ctaHref: '/?service=lawn-care#quote',
      cardsTitle: 'Servicios para propiedades de Cortland',
      cards: [
        { href: '/lawn-care/', h3: 'Corte de pasto', p: 'Corte, orillado y mantenimiento de temporada para las casas de Cortland.' },
        { href: '/#services', h3: 'Renovación de jardines', p: 'Mantillo, áreas de plantas, limpieza, hojas y mejoras de fachada para su propiedad.' },
        { href: '/tree-removal/', h3: 'Servicio de árboles', p: 'Poda, retiro, destoconado y limpieza después de ramas problemáticas o tormentas.' }
      ],
      nearH2: 'Suficientemente cerca para un servicio puntual',
      nearP:
        'Cortland está muy cerca de la base en DeKalb, lo que facilita el trabajo regular de pasto, la limpieza de temporada y las citas para presupuestos.',
      faqTitle: 'Preguntas frecuentes en Cortland',
      faq: [
        { q: '¿Cortan pasto en Cortland?', a: 'Sí. El corte y orillado de pasto están disponibles en Cortland según la ruta y la disponibilidad.' },
        { q: '¿Ayudan con la limpieza de primavera u otoño?', a: 'Sí. La limpieza puede incluir hojas, ramas, camas de jardín, orillado y renovación general del patio.' },
        { q: '¿Atienden en español?', a: 'Sí. Llame al (815) 501-1478 y con gusto revisamos su proyecto en español.' }
      ],
      breadcrumbCity: 'Cortland, IL',
      sitemapImageTitle: 'Corte de pasto en Cortland IL',
      sitemapImageCaption: 'Pasto recién terminado por Hernandez Landscape & Tree Service LLC para el área de Cortland.'
    }
  },
  {
    slug: 'malta-il',
    ownsEn: true,
    image: '/hernandez_images/google-profile-2026-completed-yard-equipment.jpg',
    en: {
      title: 'Landscaping & Tree Service in Malta, IL | Hernandez Landscape',
      description:
        'Hernandez Landscape & Tree Service LLC serves Malta, IL with lawn care, landscaping, tree trimming and removal, yard cleanup, and seasonal snow service. Call (815) 501-1478.',
      ogDescription:
        'Malta lawn care, landscaping, tree service, cleanup, and seasonal snow service from Hernandez Landscape & Tree Service LLC.',
      imageAlt: 'Completed yard work with Hernandez Landscape equipment on site near Malta Illinois',
      kicker: 'Malta, Illinois',
      h1: 'Malta lawn care, landscaping, and tree service',
      intro:
        'Malta sits a short drive west of the DeKalb shop along Route 38, so village homes and larger lots get the same local crew for routine mowing, yard cleanup, mulch and planting work, tree trimming and removal, and storm cleanup by availability.',
      ctaText: 'Request Malta estimate',
      ctaHref: '/?service=lawn-care#quote',
      cardsTitle: 'Outdoor work for Malta properties',
      cards: [
        { href: '/lawn-care/', h3: 'Lawn maintenance', p: 'Recurring mowing, trimming, and edging sized for Malta village yards and larger open lots.' },
        { href: '/tree-removal/', h3: 'Tree trimming and removal', p: 'Careful cutting, hauling, and cleanup for mature trees around older Malta properties.' },
        { href: '/#services', h3: 'Yard and seasonal cleanup', p: 'Mulch, planting beds, leaf removal, brush hauling, and seasonal property refresh work.' }
      ],
      nearH2: 'Based in DeKalb, minutes from Malta',
      nearP:
        'The crew is based on Lewis St in DeKalb, and the straight run west on Route 38 makes Malta practical for estimates, weekly routes, and scheduled cleanups.',
      faqTitle: 'Malta service FAQs',
      faq: [
        { q: 'Do you give estimates in Malta?', a: 'Yes. Malta estimates are available for lawn care, tree service, landscaping, cleanup, and snow removal by availability.' },
        { q: 'Can you handle larger village or rural lots?', a: 'Yes. Mowing, cleanup, and brush work can be scoped for bigger yards and open lots during the estimate.' },
        { q: 'Do you offer snow removal in Malta?', a: 'Seasonal snow service is offered by availability — ask when you request your estimate.' }
      ],
      breadcrumbCity: 'Malta, IL',
      sitemapImageTitle: 'Lawn and yard service in Malta IL',
      sitemapImageCaption: 'Completed yard work from Hernandez Landscape & Tree Service LLC for the Malta service area.'
    },
    es: {
      title: 'Jardinería y servicio de árboles en Malta, IL | Hernandez Landscape',
      description:
        'Corte de pasto, jardinería, poda y retiro de árboles y limpieza de patios para Malta, IL. Hernandez Landscape & Tree Service LLC — llame al (815) 501-1478.',
      ogDescription:
        'Corte de pasto, limpieza de patios, servicio de árboles y trabajo de temporada para casas y lotes de Malta.',
      imageAlt: 'Trabajo de patio terminado con equipo de Hernandez Landscape cerca de Malta, Illinois',
      kicker: 'Malta, Illinois',
      h1: 'Corte de pasto, jardinería y árboles en Malta',
      intro:
        'Malta queda a unos minutos al oeste de DeKalb por la Ruta 38. El mismo equipo local atiende casas del pueblo y lotes grandes con corte de pasto, limpieza de patios, mantillo, poda y retiro de árboles, y limpieza después de tormentas según disponibilidad.',
      ctaText: 'Pida su presupuesto en Malta',
      ctaHref: '/?service=lawn-care#quote',
      cardsTitle: 'Trabajo de patio para propiedades de Malta',
      cards: [
        { href: '/lawn-care/', h3: 'Mantenimiento de pasto', p: 'Corte y orillado regular para patios del pueblo y lotes grandes de Malta.' },
        { href: '/tree-removal/', h3: 'Poda y retiro de árboles', p: 'Cortes cuidadosos, acarreo y limpieza para árboles maduros en propiedades de Malta.' },
        { href: '/#services', h3: 'Limpieza de patio y temporada', p: 'Mantillo, camas de plantas, hojas, ramas y renovación general del patio.' }
      ],
      nearH2: 'Base en DeKalb, a minutos de Malta',
      nearP:
        'El equipo sale de DeKalb, y el camino directo por la Ruta 38 hace fácil programar presupuestos, rutas semanales y limpiezas en Malta.',
      faqTitle: 'Preguntas frecuentes en Malta',
      faq: [
        { q: '¿Dan presupuestos en Malta?', a: 'Sí. Hay presupuestos disponibles en Malta para pasto, árboles, jardinería, limpieza y nieve según disponibilidad.' },
        { q: '¿Trabajan lotes grandes o rurales?', a: 'Sí. El corte, la limpieza y el retiro de ramas se cotizan según el tamaño del terreno durante el presupuesto.' },
        { q: '¿Atienden en español?', a: 'Sí. Llame al (815) 501-1478 y explique su proyecto en español con confianza.' }
      ],
      breadcrumbCity: 'Malta, IL',
      sitemapImageTitle: 'Servicio de patio en Malta IL',
      sitemapImageCaption: 'Trabajo de patio terminado por Hernandez Landscape & Tree Service LLC para el área de Malta.'
    }
  }
];

const enUrl = (c) => `${SITE}/service-areas/${c.slug}/`;
const esUrl = (c) => `${SITE}/es/service-areas/${c.slug}/`;

/* ------------------------------------------------------------------------ */
/* Rendering                                                                  */
/* ------------------------------------------------------------------------ */

function hreflangLines(city, indent) {
  return [
    `${indent}${HREFLANG_START}`,
    `${indent}<link rel="alternate" hreflang="en" href="${enUrl(city)}" />`,
    `${indent}<link rel="alternate" hreflang="es" href="${esUrl(city)}" />`,
    `${indent}<link rel="alternate" hreflang="x-default" href="${enUrl(city)}" />`,
    `${indent}${HREFLANG_END}`
  ].join('\n');
}

function jsonLd(city, lang) {
  const t = city[lang];
  const url = lang === 'es' ? esUrl(city) : enUrl(city);
  const home = lang === 'es' ? 'Inicio' : 'Home';
  const areas = lang === 'es' ? 'Áreas de servicio' : 'Service Areas';
  const cityName = city.slug.replace(/-il$/, '').replace(/^./, (m) => m.toUpperCase());
  const doc = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'HomeAndConstructionBusiness',
        '@id': `${SITE}/#organization`,
        name: 'Hernandez Landscape & Tree Service LLC',
        url,
        image: `${SITE}${city.image}`,
        telephone: '+1-815-501-1478',
        address: {
          '@type': 'PostalAddress',
          streetAddress: '1029 Lewis St',
          addressLocality: 'DeKalb',
          addressRegion: 'IL',
          postalCode: '60115',
          addressCountry: 'US'
        },
        areaServed: { '@type': 'City', name: cityName, containedInPlace: { '@type': 'State', name: 'Illinois' } },
        knowsLanguage: ['English', 'Spanish'],
        priceRange: '$$'
      },
      {
        '@type': 'BreadcrumbList',
        '@id': `${url}#breadcrumb`,
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: home, item: `${SITE}/` },
          { '@type': 'ListItem', position: 2, name: areas, item: `${SITE}/service-areas/` },
          { '@type': 'ListItem', position: 3, name: t.breadcrumbCity, item: url }
        ]
      },
      {
        '@type': 'FAQPage',
        '@id': `${url}#faq`,
        inLanguage: lang,
        mainEntity: t.faq.map((f) => ({
          '@type': 'Question',
          name: f.q,
          acceptedAnswer: { '@type': 'Answer', text: f.a }
        }))
      }
    ]
  };
  return JSON.stringify(doc, null, 2)
    .split('\n')
    .map((line) => `    ${line}`)
    .join('\n');
}

function renderPage(city, lang) {
  const t = city[lang];
  const url = lang === 'es' ? esUrl(city) : enUrl(city);
  const otherUrl = lang === 'es' ? `/service-areas/${city.slug}/` : `/es/service-areas/${city.slug}/`;
  const otherLabel = lang === 'es' ? 'English' : 'Español';
  const quoteLabel = lang === 'es' ? 'Cotización gratis' : 'Get Free Quote';
  const cards = t.cards
    .map(
      (card) =>
        `            <a href="${card.href}" class="rounded-lg bg-white p-6 shadow-md"><h3 class="font-bold text-green-900">${card.h3}</h3><p class="mt-3 text-sm text-gray-600">${card.p}</p></a>`
    )
    .join('\n');
  const faq = t.faq
    .map(
      (f) =>
        `              <div><h3 class="font-bold">${f.q}</h3><p class="mt-2 text-sm text-gray-600">${f.a}</p></div>`
    )
    .join('\n');
  const ogLocale = lang === 'es' ? '\n    <meta property="og:locale" content="es_US" />' : '';

  return `<!doctype html>
${BANNER}
<html lang="${lang}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${t.title}</title>
    <meta name="description" content="${t.description}" />
    <meta name="robots" content="index, follow, max-image-preview:large" />
    <link rel="canonical" href="${url}" />
    ${HREFLANG_START}
    <link rel="alternate" hreflang="en" href="${enUrl(city)}" />
    <link rel="alternate" hreflang="es" href="${esUrl(city)}" />
    <link rel="alternate" hreflang="x-default" href="${enUrl(city)}" />
    ${HREFLANG_END}
    <meta property="og:title" content="${t.title}" />
    <meta property="og:description" content="${t.ogDescription}" />
    <meta property="og:image" content="${SITE}${city.image}" />
    <meta property="og:image:alt" content="${t.imageAlt}" />
    <meta property="og:url" content="${url}" />
    <meta property="og:type" content="business.business" />
    <meta property="og:site_name" content="Hernandez Landscape & Tree Service LLC" />${ogLocale}
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${t.title}" />
    <meta name="twitter:description" content="${t.ogDescription}" />
    <meta name="twitter:image" content="${SITE}${city.image}" />
    <meta name="twitter:image:alt" content="${t.imageAlt}" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <link rel="stylesheet" href="/assets/css/styles.css?v=20260519" />
    <link rel="stylesheet" href="/assets/css/custom.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" media="print" onload="this.media = 'all'" />
    <noscript><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" /></noscript>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700;900&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet" />
  </head>
  <body class="site-body bg-gray-50">
    <header class="site-header fixed top-0 z-50 w-full bg-white shadow">
      <div class="container mx-auto px-4">
        <nav class="flex items-center justify-between py-3">
          <a href="/" class="flex items-center gap-3">
            <img src="/hernandez_images/web_Logo_New_256.png" alt="Hernandez Landscape & Tree Service LLC Logo" class="h-12 w-auto object-contain" />
            <span class="text-lg font-bold text-gray-800">Hernandez Landscape</span>
          </a>
          <div class="flex items-center gap-4">
            <a href="${otherUrl}" class="text-sm font-semibold text-gray-600 hover:text-green-700" lang="${lang === 'es' ? 'en' : 'es'}">${otherLabel}</a>
            <a href="/#quote" class="rounded-full bg-green-600 px-6 py-2 text-sm font-bold text-white shadow-md hover:bg-green-700">${quoteLabel}</a>
          </div>
        </nav>
      </div>
    </header>

    <main class="pt-28">
      <section class="bg-white">
        <div class="container mx-auto grid gap-8 px-4 py-14 lg:grid-cols-[1fr_0.9fr] lg:items-center">
          <div>
            <p class="mb-3 text-sm font-bold uppercase tracking-wide text-green-700">${t.kicker}</p>
            <h1 class="text-4xl font-black leading-tight text-gray-900 md:text-5xl">${t.h1}</h1>
            <p class="mt-5 text-lg leading-relaxed text-gray-600">${t.intro}</p>
            <div class="mt-7 flex flex-col gap-3 sm:flex-row">
              <a href="${t.ctaHref}" class="rounded-full bg-green-600 px-7 py-3 text-center font-bold text-white hover:bg-green-700">${t.ctaText}</a>
              <a href="tel:18155011478" class="rounded-full border-2 border-green-700 px-7 py-3 text-center font-bold text-green-800 hover:bg-green-50">(815) 501-1478</a>
            </div>
          </div>
          <img src="${city.image}" alt="${t.imageAlt}" class="h-96 w-full rounded-lg object-cover shadow-xl" />
        </div>
      </section>

      <section class="py-14">
        <div class="container mx-auto px-4">
          <h2 class="text-3xl font-bold text-gray-900">${t.cardsTitle}</h2>
          <div class="mt-8 grid gap-6 md:grid-cols-3">
${cards}
          </div>
        </div>
      </section>

      <section class="bg-white py-14">
        <div class="container mx-auto grid gap-8 px-4 lg:grid-cols-2">
          <div>
            <h2 class="text-2xl font-bold text-gray-900">${t.nearH2}</h2>
            <p class="mt-4 text-gray-600">${t.nearP}</p>
          </div>
          <div class="rounded-lg bg-green-50 p-6">
            <h2 class="text-2xl font-bold text-gray-900">${t.faqTitle}</h2>
            <div class="mt-5 space-y-5">
${faq}
            </div>
          </div>
        </div>
      </section>
    </main>

    <footer class="bg-gray-900 py-8 text-center text-white">
      <p class="text-sm text-gray-400">&copy; 2026 Hernandez Landscape & Tree Service LLC. 1029 Lewis St, DeKalb, IL 60115 | (815) 501-1478</p>
    </footer>

    <script type="application/ld+json">
${jsonLd(city, lang)}
    </script>
  <script src="/assets/js/analytics.js" defer></script>
  <script src="/assets/js/mobile-call-cta.js" defer></script>
  </body>
</html>
`;
}

/* ------------------------------------------------------------------------ */
/* hreflang injection into hand-written EN pages                              */
/* ------------------------------------------------------------------------ */

function injectHreflang(html, city) {
  const indentMatch = html.match(/^([ \t]*)<link rel="canonical"/m);
  const indent = indentMatch ? indentMatch[1] : '    ';
  const block = hreflangLines(city, indent);

  const startIdx = html.indexOf(HREFLANG_START);
  if (startIdx !== -1) {
    const endIdx = html.indexOf(HREFLANG_END);
    if (endIdx === -1) throw new Error(`${city.slug}: HREFLANG start marker without end marker`);
    const before = html.slice(0, html.lastIndexOf('\n', startIdx) + 1);
    const after = html.slice(html.indexOf('\n', endIdx));
    return `${before}${block}${after}`;
  }

  const canonicalLine = html.match(/^[ \t]*<link rel="canonical"[^\n]*\n/m);
  if (!canonicalLine) throw new Error(`${city.slug}: no canonical link found to anchor hreflang block`);
  return html.replace(canonicalLine[0], `${canonicalLine[0]}${block}\n`);
}

/* ------------------------------------------------------------------------ */
/* sitemap block                                                              */
/* ------------------------------------------------------------------------ */

function sitemapEntry(loc, image, title, caption) {
  return [
    '  <url>',
    `    <loc>${loc}</loc>`,
    `    <lastmod>${LASTMOD}</lastmod>`,
    '    <changefreq>monthly</changefreq>',
    '    <priority>0.7</priority>',
    '    <image:image>',
    `      <image:loc>${SITE}${image}</image:loc>`,
    `      <image:title>${title}</image:title>`,
    `      <image:caption>${caption.replaceAll('&', '&amp;')}</image:caption>`,
    '    </image:image>',
    '  </url>'
  ].join('\n');
}

function sitemapBlock() {
  const entries = [];
  for (const city of CITY_PAGES) {
    if (city.ownsEn) {
      entries.push(sitemapEntry(enUrl(city), city.image, city.en.sitemapImageTitle, city.en.sitemapImageCaption));
    }
    entries.push(sitemapEntry(esUrl(city), city.image, city.es.sitemapImageTitle, city.es.sitemapImageCaption));
  }
  return `  ${SITEMAP_START}\n${entries.join('\n')}\n  ${SITEMAP_END}`;
}

function updateSitemap(xml) {
  const block = sitemapBlock();
  const startIdx = xml.indexOf(SITEMAP_START);
  if (startIdx !== -1) {
    const endIdx = xml.indexOf(SITEMAP_END);
    if (endIdx === -1) throw new Error('sitemap.xml: LOCAL-PAGES start marker without end marker');
    const before = xml.slice(0, xml.lastIndexOf('\n', startIdx) + 1);
    const after = xml.slice(xml.indexOf('\n', endIdx));
    return `${before}${block}${after}`;
  }
  return xml.replace(/^<\/urlset>/m, `${block}\n</urlset>`);
}

/* ------------------------------------------------------------------------ */
/* run                                                                        */
/* ------------------------------------------------------------------------ */

const outputs = [];

for (const city of CITY_PAGES) {
  if (city.ownsEn) {
    outputs.push({ rel: `service-areas/${city.slug}/index.html`, content: renderPage(city, 'en') });
  } else {
    const rel = `service-areas/${city.slug}/index.html`;
    const existing = fs.readFileSync(path.join(ROOT, rel), 'utf8');
    outputs.push({ rel, content: injectHreflang(existing, city) });
  }
  outputs.push({ rel: `es/service-areas/${city.slug}/index.html`, content: renderPage(city, 'es') });
}

outputs.push({ rel: 'sitemap.xml', content: updateSitemap(fs.readFileSync(path.join(ROOT, 'sitemap.xml'), 'utf8')) });

const drifted = [];
for (const { rel, content } of outputs) {
  const abs = path.join(ROOT, rel);
  const current = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
  if (current === content) continue;
  drifted.push(rel);
  if (!CHECK) {
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content);
  }
}

if (CHECK) {
  if (drifted.length) {
    console.error(`generate_local_pages --check: ${drifted.length} file(s) out of sync:`);
    for (const rel of drifted) console.error(`  - ${rel}`);
    console.error('Run: node scripts/generate_local_pages.js');
    process.exit(1);
  }
  console.log(`generate_local_pages --check: ${outputs.length} files in sync.`);
} else {
  console.log(`generate_local_pages: ${outputs.length} files managed, ${drifted.length} written.`);
  for (const rel of drifted) console.log(`  ~ ${rel}`);
}
